version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./.databases/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "devdb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "Qq111111"
      PGDATA: "/var/lib/postgresql/data/pgdata"
